<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <xacro:property name="short_arm_length" value="0.065"/>
    <xacro:property name="long_arm_length" value="0.194"/>



    <xacro:macro name="long_arm" params="number">

<!--ELBOW JOINT FOR X ROTATION-->

        <joint name="elbow${number}_x_joint" type="revolute">
            <parent link="short_arm${number}_link"/>
            <child link="elbow${number}_link"/>
            <origin xyz="0 ${short_arm_length} 0" rpy="0 0 0"/>
            <axis xyz="1 0 0"/>
            <limit lower="-1.5708" upper="1.5708" effort=".12" velocity="5"/>
            <dynamics damping="1.0" friction="0.2"/>
        </joint>


    <!--ELBOW X LINK-->

        <link name="elbow${number}_link">
            <visual>
                <material name="white"/>
                <geometry>
                    <sphere radius="0.005"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.060"/>
                <inertia
                    ixx="0.00001" ixy="0.0" ixz="0.0"
                    iyy="0.0000065" iyz="0.0"
                    izz="0.0000125"/>
            </inertial>
        </link>

    <!--ELBOW Z LINK-->

        <joint name="elbow${number}_y_joint" type="revolute">
            <parent link="elbow${number}_link"/>
            <child link="long_arm${number}_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit lower="-1.5708" upper="1.5708" effort=".12" velocity="5"/>
            <dynamics damping="1.0" friction="0.2"/>
        </joint>


        <link name="long_arm${number}_link">
            <visual>
                <material name="white"/>
                <geometry>
                    <cylinder length = "${long_arm_length}" radius = "0.0025"/>
                </geometry>
                <origin xyz="0 ${long_arm_length / 2 } 0" rpy="1.5708 0 0"/>
            </visual>

            <inertial>
                <origin xyz="0 ${long_arm_length / 2 } 0" rpy="1.5708 0 0"/>
                <mass value="0.060"/>
                <inertia
                    ixx="0.00001" ixy="0.0" ixz="0.0"
                    iyy="0.0000065" iyz="0.0"
                    izz="0.0000125"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:long_arm number="1"/>
    <xacro:long_arm number="2"/>
    <xacro:long_arm number="3"/>
    <xacro:long_arm number="4"/>
    <xacro:long_arm number="5"/>
    <xacro:long_arm number="6"/>


</robot>